In [ ]:
#VARIABLE AND STRING CONCATINATION
a=10
print("i'm",a,"years old")

i'm 10 years old


a=int(input("enter a value"))
b=int(input("enter b value"))
print(a+b,"=sum")


In [ ]:
#ADDING TWO INTEGER VALUES
a=int(input("enter a value"))
b=int(input("enter b value"))
print("sum=",a+b)
print("difference=",a-b)
print("product=",a*b)
print("quatient=",a/b)
print("remainder=",a%b)
print("power of a to b=",a**b)

enter a value2
enter b value4
sum= 6
difference= -2
product= 8
quatient= 0.5
remainder= 2
power of a to b= 16


In [ ]:
#Take a salary from the user,if the salary is more than 50000 than tax is 10% and print final salary
salary=int(input("Enter your sarlary="))
if(salary>=50000):
  final_salary=salary-salary*(0.1)
  print("final salary =",final_salary)
else:
 print("Your Salary is less than 50000,without tax is :",salary)

Enter your sarlary=50000
final salary = 45000.0


In [ ]:
#get the salary from the user , if the is more or equal to 50000 apply 10% reduction , if the salary is < 50000 apply %5 , if the salary is more than 70000 apply 12% tax and if salary exceeds
salary=int(input("Enter your sarlary="))
if(salary<50000):
  final_salary=salary-salary*(0.05)
  print("final salary =",final_salary)
elif(salary<=70000):
  final_salary=salary-salary*(0.1)
  print("final salary =",final_salary)
elif(salary<=100000):
  final_salary=salary-salary*(0.12)
  print("final salary =",final_salary)
else:
  print("You are promoted")

Enter your sarlary=0
final salary = 0.0


In [ ]:
#Range Fuction
T=int(input("Enter a number="))
for i in range(1,31,5):
  print(T,"x",i,"=",T*i)

Enter a number=5
5 x 1 = 5
5 x 6 = 30
5 x 11 = 55
5 x 16 = 80
5 x 21 = 105
5 x 26 = 130


In [ ]:
#while loop
T=int(input("Enter a number="))
i=1
while(i!=11):
  print(T,"x",i,"=",T*i)
  i=i+1

Enter a number=5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
#Creating List
L=[20,15,25,51,5]
L1=["UMP9","VECTOR","m416","UZI","DP29","M762"]
L1.append("MG3")
L1.pop(2)
print(L[::-1])
print(L1[::-1])
L2=L+L1
print(L)
print(L1)
print(L2)

[5, 51, 25, 15, 20]
['MG3', 'M762', 'DP29', 'UZI', 'VECTOR', 'UMP9']
[20, 15, 25, 51, 5]
['UMP9', 'VECTOR', 'UZI', 'DP29', 'M762', 'MG3']
[20, 15, 25, 51, 5, 'UMP9', 'VECTOR', 'UZI', 'DP29', 'M762', 'MG3']


In [ ]:
#Reverse Of A List
L=[20,15,25,51,5]
L1=["UMP9","VECTOR","m416","UZI","DP29","M762"]
print(L[::-1])
print(L1[::-1])

[5, 51, 25, 15, 20]
['M762', 'DP29', 'UZI', 'm416', 'VECTOR', 'UMP9']


In [ ]:
#POP
L=[20,15,25,51,5]
L1=["UMP9","VECTOR","m416","UZI","DP29","M762"]
L1.pop(3)
print(L1)

['UMP9', 'VECTOR', 'm416', 'DP29', 'M762']


In [ ]:
#Remove
L=[20,15,25,51,5]
L1=["UMP9","VECTOR","m416","UZI","DP29","M762"]
L.remove(51)
print(L)

[20, 15, 25, 5]


In [ ]:
#Append
L=[20,15,25,51,5]
L1=["UMP9","VECTOR","m416","UZI","DP29","M762"]
L.append(55)
print(L)

[20, 15, 25, 51, 5, 55]


In [ ]:
#Create a list of 10 integers elements and print their squares and saves these squares in a new list
L=[1,2,3,4,5,6,7,8,9,10]
L1=[]
for i in L:
  L1.append(i*i)
print(L1)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comperhension
L=[1,2,3,4,5,6,7,8,9,10]
L2=[ i*i for i in L]
print(L2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comperhension With a Condition
L=[1,2,3,4,5,6,7,8,9,10]
L2=[ i*i for i in L if i<=5]
print(L2)

[1, 4, 9, 16, 25]


In [5]:
#list comperhension With a Conditions
L=[15,51,59,32,45,87]
L2=[ i*i if i>50 else 'X' for i in L]
print(L2)

['X', 2601, 3481, 'X', 'X', 7569]


In [6]:
#Take the salary the user if the salary IS < 50K / 10% TAX Otherwise 15%
salary=int(input("Enter the salary:"))
print("The final salary :",salary-salary*(0.1) if(salary<=50000) else salary-salary*(0.15))

Enter the salary:60000
The final salary : 51000.0


In [7]:
#OTHER METHOD FOR [Take the salary the user if the salary IS < 50K / 10% TAX Otherwise 15%]
salary=[45000,50000,60000,70000,80000]
newlist=[i-i*0.1 if i<50000 else i-i*0.15 for i in salary]
print(newlist)

[40500.0, 42500.0, 51000.0, 59500.0, 68000.0]


In [8]:
#Dictionary
dict1={"Game":'PUBG',"Year":'2006',"Type":'BATTLE',"AWM":'300 MAG'}
print(dict1)
print(dict1.keys())
print(dict1.values())

{'Game': 'PUBG', 'Year': '2006', 'Type': 'BATTLE', 'AWM': '300 MAG'}
dict_keys(['Game', 'Year', 'Type', 'AWM'])
dict_values(['PUBG', '2006', 'BATTLE', '300 MAG'])


In [9]:
#Dictionary
#keys
dict1={"Game":'PUBG',"Year":'2006',"Type":'BATTLE',"AWM":'300 MAG'}
print(dict1.keys())

dict_keys(['Game', 'Year', 'Type', 'AWM'])


In [10]:
#Dictionary
#values
dict1={"Game":'PUBG',"Year":'2006',"Type":'BATTLE',"AWM":'300 MAG'}
print(dict1.values())

dict_values(['PUBG', '2006', 'BATTLE', '300 MAG'])


In [15]:
#Dictionary
#printing a particular value
dict1={"Game":'PUBG',"Year":'2006',"Type":'BATTLE',"AWM":'300 MAG'}
print(dict1["Game"])

PUBG


In [22]:
#Dictionary's
dict2={"Dept":'CSE',"Details":{"Year":'2nd year',"section":'D',"strength":'73'}}
print("Years is",dict2["Details"]["Year"])
print("DEPARTMENT IS",dict2["Dept"])
print("section is",dict2["Details"]["section"])
print("strength is",dict2["Details"]["strength"])

Years is 2nd year
DEPARTMENT IS CSE
section is D
strength is 73


In [23]:
#Dictionary's Using ZipFile
id=[1,2,3,4,5,6]
names=["BINNU","SAKULJI","SHIVA","DILEEP","SHUBHAS","SHANKAR"]
new=zip(id,names)
for i in new:
  print(i)

(1, 'BINNU')
(2, 'SAKULJI')
(3, 'SHIVA')
(4, 'DILEEP')
(5, 'SHUBHAS')
(6, 'SHANKAR')


In [31]:
import numpy as np
A = np.array([1,2,3,4]) #1D ARRAY
print(A.ndim)
print(A.shape)

1
(4,)


In [42]:
import numpy as np
A = np.array([[1,8],[2,9],[3,7],[4,5]]) #2D ARRAY
print(A.ndim)
print(A.shape)

2
(4, 2)


In [43]:
import numpy as np
A = np.array([[[1,2,5],[2,6,5],[3,8,4],[4,8,9]],[[9,8,2],[8,8,1],[7,8,1],[6,5,6]]]) #3D ARRAY
print(A.ndim)
print(A.shape)

3
(2, 4, 3)


In [44]:
A = np.ones((2,4,3))
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [45]:
A = np.zeros((2,4,3))
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [46]:
A = np.ones((1,4,3))
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [47]:
A = np.ones((2,2,3))
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [48]:
A = np.ones((2,2,2))
print(A)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [56]:
A = np.arange(8,1001,8)
print(A)
print(type(A))


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [59]:
A = np.linspace(4,6,24)
print(A)

[4.         4.08695652 4.17391304 4.26086957 4.34782609 4.43478261
 4.52173913 4.60869565 4.69565217 4.7826087  4.86956522 4.95652174
 5.04347826 5.13043478 5.2173913  5.30434783 5.39130435 5.47826087
 5.56521739 5.65217391 5.73913043 5.82608696 5.91304348 6.        ]
